import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-list-recruiter',
  templateUrl: './list-recruiter.component.html',
  styleUrls: ['./list-recruiter.component.scss'],
})
export class ListRecruiterComponent implements OnInit {
  constructor() {}
  paginate: any = '';

  ngOnInit(): void {}

  condidatsList: any = [
    {
      avalilaible: true,
      img: 'https://avatars.githubusercontent.com/u/71600486?v=4',
      name: 'Ahmed Aoulad Amar',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
      
    },
    {
      avalilaible: false,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar2.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar4.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar5.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar6.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar7.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar8.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar9.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar10.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
    {
      avalilaible: true,
      img: 'https://www.bootdey.com/img/Content/avatar/avatar3.png',
      name: 'ahmed aoulad amr',
      age: '25',
      address: 'tanger/morococ',
      tital_job: 'web developer',
      years_of_ex: '2 years',
      ed_lavel: 'bac + 3',
      tag: ['web', 'developer'],
    },
  ];
}
